var words = 
[
{"pingyin":"he","char":"他"},
{"pingyin":"docker","char":"医生"},
{"pingyin":"she","char":"她"},
{"pingyin":"me","char":"我"},
{"pingyin":"nurse","char":"护士"},
{"pingyin":"driver","char":"司机"},
{"pingyin":"policeman","char":"警察"},
{"pingyin":"pupil","char":"学生，小学生"},
{"pingyin":"where","char":"哪里"},
{"pingyin":"in","char":"在......里"},
{"pingyin":"on","char":"在......上"},
{"pingyin":"hat","char":"帽子"},
{"pingyin":"under","char":"在......下"},
{"pingyin":"toy","char":"玩具"},
{"pingyin":"bed","char":"床"},
{"pingyin":"look","char":"看"},
{"pingyin":"bear","char":"熊"},
{"pingyin":"eleven","char":"十一"},
{"pingyin":"twelve","char":"十二"},
{"pingyin":"don't = do not","char":"不"},
{"pingyin":"know","char":"知道"},
{"pingyin":"other","char":"其他"},
{"pingyin":"fish","char":"鱼"},
{"pingyin":"tree","char":"树"},
{"pingyin":"let's","char":"让我们"},
{"pingyin":"head","char":"头"},
{"pingyin":"touch","char":"触摸"},
{"pingyin":"eye","char":"眼睛"},
{"pingyin":"body","char":"身体"},
{"pingyin":"these","char":"这些"},
{"pingyin":"leg","char":"腿"},
{"pingyin":"hand","char":"手"},
{"pingyin":"feet","char":"脚（foot的复数形式）"},
{"pingyin":"baby","char":"婴儿"},
{"pingyin":"they","char":"他（她/它)们"},
{"pingyin":"they're = they are","char":"他（她/它)们是"},
{"pingyin":"cow","char":"奶牛"},
{"pingyin":"pig","char":"猪"},
{"pingyin":"farm","char":"农场"},
{"pingyin":"duck","char":"鸭子"},
{"pingyin":"chicken","char":"鸡"},
{"pingyin":"egg","char":"鸡蛋，蛋"},
{"pingyin":"thin","char":"瘦的"},
{"pingyin":"very","char":"很，非常"},
{"pingyin":"fat","char":"胖的"},
{"pingyin":"big","char":"大的"},
{"pingyin":"litte","char":"小的"},
{"pingyin":"snake","char":"蛇"},
{"pingyin":"short","char":"矮的，短的"},
{"pingyin":"small","char":"小的"},
{"pingyin":"elephant","char":"大象"},
{"pingyin":"go","char":"去"},
{"pingyin":"zoo","char":"动物园"},
{"pingyin":"long","char":"长的"},
{"pingyin":"giraffe","char":"长颈鹿"},
{"pingyin":"tall","char":"高的"},
{"pingyin":"tiger","char":"老虎"},
{"pingyin":"cute","char":"可爱的，乖巧的"},
{"pingyin":"strong","char":"强壮的"},
{"pingyin":"horse","char":"马"},
{"pingyin":"aren't = are not","char":"不，不是"},
{"pingyin":"there is","char":"有，存在"},
{"pingyin":"animal","char":"动物"},
{"pingyin":"can","char":"可以，能"},
{"pingyin":"see","char":"看见"},
{"pingyin":"there are","char":"有，存在"},
{"pingyin":"help","char":"帮助"},
{"pingyin":"over there","char":"在那边"},
{"pingyin":"table","char":"桌子"},
{"pingyin":"we","char":"我们"},
{"pingyin":"some","char":"一些"},
{"pingyin":"at","char":"在"},
{"pingyin":"a pair of","char":"一双，一对"},
{"pingyin":"swim","char":"游泳"},
{"pingyin":"OK","char":"行，好"},
{"pingyin":"sock","char":"短袜"},
{"pingyin":"put on","char":"穿上，戴上"},
{"pingyin":"clothes","char":"（常复）衣服"},
{"pingyin":"here","char":"这里"},
{"pingyin":"football","char":"足球"},
{"pingyin":"basketball","char":"篮球"},
{"pingyin":"ping-pong","char":"乒乓球"},
{"pingyin":"like","char":"喜欢"},
{"pingyin":"lion","char":"狮子"},
{"pingyin":"them","char":"他们"},
{"pingyin":"all","char":"全部，所有"},
{"pingyin":"play","char":"参加"},
{"pingyin":"with","char":"用......"},
{"pingyin":"together","char":"一起"},
{"pingyin":"favourite","char":"最喜欢的"},
{"pingyin":"sport","char":"运动"},
{"pingyin":"guess","char":"猜"},
{"pingyin":"what about...?","char":"...怎么样？"},
{"pingyin":"swimming","char":"游泳"},
{"pingyin":"idea","char":"主意，想法"},
{"pingyin":"hot","char":"热的"},
{"pingyin":"go swimming","char":"去游泳"},
{"pingyin":"sing","char":"唱，唱歌"},
{"pingyin":"dance","char":"跳舞"},
{"pingyin":"tired","char":"累的，疲惫的"}
]
var sentences = [] 
module.exports = {words, sentences }